---
apiVersion: v1
kind: Service
metadata:
  name: k8s-webshell
  namespace: production-k8s-webshell # 根据自己的情况进行修改
spec:
  selector:
    app: k8s-webshell
  type: NodePort
  ports:
    - name: http
      port: 7777
      targetPort: 7777
      nodePort: 30001
      protocol: TCP