server:
  port: 7777
  run_mode: debug
  logpath: /tmp/k8s-webshell
  logname: webshell.log
  certificate: /Users/richie/data/certbot-data/etc/letsencrypt/live/webshell-test.zrq.org.cn-0001/fullchain.pem
  certificatekey: /Users/richie/data/certbot-data/etc/letsencrypt/live/webshell-test.zrq.org.cn-0001/privkey.pem
  jwtsecret: YouGuess
  secretkey: richie

k8s:
  kubeconfig: /Users/richie/.kube/config
  incluster: false


