server:
  port: 7777
  run_mode: debug
  logpath: /Users/finup/GoglandProjects/src/k8s-webshell
  logname: webshell.log
  certificate: /Users/finup/GolandProjects/src/k8s-webshell/configs/inside_finup.crt
  certificatekey: /Users/finup/GolandProjects/src/k8s-webshell/configs/inside_finup.key
  jwtsecret: YouGuess
  secretkey: richie

k8s:
  kubeconfig: /Users/finup/finupdata/go-projects/k8s-webshell/configs/admin.conf
  incluster: false


