server:
  port: 7777
  run_mode: debug
  logpath: /Users/finup/GoglandProjects/src/k8s-webshell
  logname: webshell.log
  kubeconfig: /Users/finup/GoglandProjects/src/k8s-webshell/configs/admin.conf


