server:
  port: 7777
  run_mode: debug
  logpath: /tmp/k8s-webshell
  logname: webshell.log
  kubeconfig: /Users/finup/GoglandProjects/src/k8s-webshell/configs/admin.conf
  incluster: false
  ssl_certificate: /Users/finup/GoglandProjects/src/k8s-webshell/configs/inside_finup.crt
  ssl_certificate_key: /Users/finup/GoglandProjects/src/k8s-webshell/configs/inside_finup.key
